export const browserCoreExamples = [
  "minion browser status",
  "minion browser start",
  "minion browser stop",
  "minion browser tabs",
  "minion browser open https://example.com",
  "minion browser focus abcd1234",
  "minion browser close abcd1234",
  "minion browser screenshot",
  "minion browser screenshot --full-page",
  "minion browser screenshot --ref 12",
  "minion browser snapshot",
  "minion browser snapshot --format aria --limit 200",
  "minion browser snapshot --efficient",
  "minion browser snapshot --labels",
];

export const browserActionExamples = [
  "minion browser navigate https://example.com",
  "minion browser resize 1280 720",
  "minion browser click 12 --double",
  'minion browser type 23 "hello" --submit',
  "minion browser press Enter",
  "minion browser hover 44",
  "minion browser drag 10 11",
  "minion browser select 9 OptionA OptionB",
  "minion browser upload /tmp/minion/uploads/file.pdf",
  'minion browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "minion browser dialog --accept",
  'minion browser wait --text "Done"',
  "minion browser evaluate --fn '(el) => el.textContent' --ref 7",
  "minion browser console --level error",
  "minion browser pdf",
];
