name: Setup Node.js environment
description: >
  Sets up Node.js, pnpm (with cache), and installs dependencies.
  Consolidates the 5-step Node setup sequence used across CI jobs.
inputs:
  node-version:
    required: false
    default: "22.x"
  pnpm-version:
    required: false
    default: "10.23.0"
  install-deps:
    description: Whether to run pnpm install
    required: false
    default: "true"
  install-flags:
    description: Extra flags for pnpm install
    required: false
    default: "--frozen-lockfile --ignore-scripts=false --config.engine-strict=false --config.enable-pre-post-scripts=true"
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        check-latest: true

    - name: Setup pnpm + cache
      uses: ./.github/actions/setup-pnpm-store-cache
      with:
        pnpm-version: ${{ inputs.pnpm-version }}
        cache-key-suffix: "node${{ inputs.node-version }}"

    - name: Runtime versions
      shell: bash
      run: node -v && npm -v && pnpm -v

    - name: Capture node path
      shell: bash
      run: echo "NODE_BIN=$(dirname "$(node -p "process.execPath")")" >> "$GITHUB_ENV"

    - name: Install dependencies
      if: ${{ inputs.install-deps == 'true' }}
      shell: bash
      env:
        CI: true
      run: |
        export PATH="$NODE_BIN:$PATH"
        pnpm install ${{ inputs.install-flags }} || pnpm install ${{ inputs.install-flags }}
