/**
 * Build-time template embedding — reads workspace templates from
 * docs/reference/templates/ and generates a TypeScript module with
 * the content inlined as a Record<string, string>.
 *
 * Usage: npx tsx scripts/embed-templates.ts
 *
 * Output: src/agents/embedded-templates.generated.ts
 */

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..");
const TEMPLATE_DIR = path.join(REPO_ROOT, "docs", "reference", "templates");
const OUTPUT_FILE = path.join(REPO_ROOT, "src", "agents", "embedded-templates.generated.ts");

export async function embedTemplates(
  templateDir: string = TEMPLATE_DIR,
): Promise<Record<string, string>> {
  const entries = await fs.readdir(templateDir, { withFileTypes: true });
  const templates: Record<string, string> = {};

  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith(".md")) {
      continue;
    }
    const content = await fs.readFile(path.join(templateDir, entry.name), "utf-8");
    templates[entry.name] = content;
  }

  return templates;
}

export function generateModule(templates: Record<string, string>): string {
  const lines: string[] = [
    "// AUTO-GENERATED by scripts/embed-templates.ts — do not edit manually.",
    `// Generated at: ${new Date().toISOString()}`,
    "",
    "/**",
    " * Embedded workspace templates for use when filesystem templates are unavailable.",
    " *",
    ' * Key: template filename (e.g. "BOOTSTRAP.md")',
    " * Value: template content string",
    " */",
    "export const EMBEDDED_TEMPLATES: Record<string, string> = {",
  ];

  for (const [name, content] of Object.entries(templates).toSorted(([a], [b]) =>
    a.localeCompare(b),
  )) {
    const escaped = JSON.stringify(content);
    lines.push(`  ${JSON.stringify(name)}: ${escaped},`);
  }

  lines.push("};");
  lines.push("");
  return lines.join("\n");
}

async function main() {
  const templates = await embedTemplates();
  const count = Object.keys(templates).length;

  if (count === 0) {
    console.error(`No .md templates found in ${TEMPLATE_DIR}`);
    process.exit(1);
  }

  const module = generateModule(templates);
  await fs.writeFile(OUTPUT_FILE, module, "utf-8");
  console.log(`Embedded ${count} templates into ${path.relative(REPO_ROOT, OUTPUT_FILE)}`);
}

if (process.argv[1]?.endsWith("embed-templates.ts")) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}
