#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${MINION_INSTALL_E2E_IMAGE:-${MINIONBOT_INSTALL_E2E_IMAGE:-minion-install-e2e:local}}"
INSTALL_URL="${MINION_INSTALL_URL:-${MINIONBOT_INSTALL_URL:-https://minion.bot/install.sh}}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
MINION_E2E_MODELS="${MINION_E2E_MODELS:-${MINIONBOT_E2E_MODELS:-}}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker/install-sh-e2e"

echo "==> Run E2E installer test"
docker run --rm \
  -e MINION_INSTALL_URL="$INSTALL_URL" \
  -e MINION_INSTALL_TAG="${MINION_INSTALL_TAG:-${MINIONBOT_INSTALL_TAG:-latest}}" \
  -e MINION_E2E_MODELS="$MINION_E2E_MODELS" \
  -e MINION_INSTALL_E2E_PREVIOUS="${MINION_INSTALL_E2E_PREVIOUS:-${MINIONBOT_INSTALL_E2E_PREVIOUS:-}}" \
  -e MINION_INSTALL_E2E_SKIP_PREVIOUS="${MINION_INSTALL_E2E_SKIP_PREVIOUS:-${MINIONBOT_INSTALL_E2E_SKIP_PREVIOUS:-0}}" \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
