// AUTO-GENERATED by scripts/embed-templates.ts — do not edit manually.
// Placeholder — run `npx tsx scripts/embed-templates.ts` to populate.

/**
 * Embedded workspace templates for use when filesystem templates are unavailable.
 *
 * Key: template filename (e.g. "BOOTSTRAP.md")
 * Value: template content string
 */
export const EMBEDDED_TEMPLATES: Record<string, string> = {};
