#!/bin/bash
# Auto-generated by fork-sync Phase 1.7
# Generated: 2026-02-19T00:00:00Z
# Mirror head: 781b1c1e0ad93050ba57d855e49b26e08a80e8b6
# Counts: 0 keepOurs, 7 manualMerge, 45 rebrand, 0 extpkg, 0 deletions, 0 autoAccept
# DO NOT EDIT — regenerate via Phase 1.7
#
# NOTE: Requires GNU sed (Linux default). On macOS: brew install gnu-sed && alias sed=gsed

set -e

# Comprehensive rebrand sed — handles:
#   - TypeScript import/require: 'openclaw' → '@nikolasp98/minion'
#   - Env vars: OPENCLAW_* → MINION_*
#   - TypeScript types: OpenClawConfig → MinionConfig
#   - Test path strings: openclaw-* → minion-*
REBRAND='s/from '"'"'openclaw'"'"'/from '"'"'@nikolasp98\/minion'"'"'/g
s/from "openclaw"/from "@nikolasp98\/minion"/g
s/require('"'"'openclaw'"'"')/require('"'"'@nikolasp98\/minion'"'"')/g
s/require("openclaw")/require("@nikolasp98\/minion")/g
s/OPENCLAW_GATEWAY_TOKEN/MINION_GATEWAY_TOKEN/g
s/OPENCLAW_GATEWAY_PASSWORD/MINION_GATEWAY_PASSWORD/g
s/OPENCLAW_SKIP_CANVAS_HOST/MINION_SKIP_CANVAS_HOST/g
s/OPENCLAW_PROFILE/MINION_PROFILE/g
s/OPENCLAW_STATE_DIR/MINION_STATE_DIR/g
s/OPENCLAW_CONFIG_PATH/MINION_CONFIG_PATH/g
s/OPENCLAW_GATEWAY_PORT/MINION_GATEWAY_PORT/g
s/OPENCLAW_SERVICE_VERSION/MINION_SERVICE_VERSION/g
s/OPENCLAW_SERVICE_MARKER/MINION_SERVICE_MARKER/g
s/OPENCLAW_SERVICE_KIND/MINION_SERVICE_KIND/g
s/OPENCLAW_BROWSER_AUTO_AUTH/MINION_BROWSER_AUTO_AUTH/g
s/OPENCLAW_LOAD_SHELL_ENV/MINION_LOAD_SHELL_ENV/g
s/OPENCLAW_DEFER_SHELL_ENV_FALLBACK/MINION_DEFER_SHELL_ENV_FALLBACK/g
s/OPENCLAW_SHELL_ENV_TIMEOUT_MS/MINION_SHELL_ENV_TIMEOUT_MS/g
s/OPENCLAW_NODE_EXEC_HOST/MINION_NODE_EXEC_HOST/g
s/OPENCLAW_NODE_EXEC_FALLBACK/MINION_NODE_EXEC_FALLBACK/g
s/OPENCLAW_RAW_STREAM/MINION_RAW_STREAM/g
s/OPENCLAW_CLAUDE_CLI_LOG_OUTPUT/MINION_CLAUDE_CLI_LOG_OUTPUT/g
s/OPENCLAW_GIT_DIR/MINION_GIT_DIR/g
s/OpenClawConfig/MinionConfig/g
s/openclaw-compaction-/minion-compaction-/g
s/openclaw-followup/minion-followup/g
s/openclaw-boot-/minion-boot-/g
s/openclaw-gateway-test/minion-gateway-test/g
s/openclaw-mem-async-/minion-mem-async-/g
s/openclaw-camera-snap/minion-camera-snap/g
s/openclaw-screen-record/minion-screen-record/g
s/openclaw-test-/minion-test-/g
s/openclaw#/minion#/g
s/provider: "openclaw"/provider: "minion"/g
s/__openclaw__/__minion__/g
s/openclaw\.json/minion.json/g'

EXT_PKG='s/"openclaw": "workspace:\*"/"@nikolasp98\/minion": "workspace:*"/g'

resolve() {
  local f="$1"
  local strategy="$2"
  # Idempotent: skip if not currently conflicted
  git ls-files -u -- "$f" | grep -q . || return 0
  case "$strategy" in
    ours)    git checkout --ours "$f" 2>/dev/null && git add "$f" && echo "✓ ours:    $f" ;;
    theirs)  git checkout --theirs "$f" 2>/dev/null && git add "$f" && echo "✓ theirs:  $f" ;;
    rebrand) git checkout --theirs "$f" 2>/dev/null && sed -i "$REBRAND" "$f" && git add "$f" && echo "✓ rebrand: $f" ;;
    extpkg)  git checkout --theirs "$f" 2>/dev/null && sed -i "$EXT_PKG" "$f" && git add "$f" && echo "✓ extpkg:  $f" ;;
    rm)      git rm -f "$f" 2>/dev/null && echo "✓ removed: $f" || true ;;
    *) echo "ERROR: unknown strategy '$strategy' for '$f'" >&2; return 1 ;;
  esac
}

echo "=== Fork-sync Phase 2: Auto-resolving merge conflicts ==="
echo "  Strategy: rebrand (upstream + MINION/MinionConfig substitutions)"
echo ""

# === rebrand (45 files) ===
# Accept upstream functional changes + apply comprehensive rebrand sed

# agents
resolve "src/agents/auth-health.ts" rebrand
resolve "src/agents/pi-embedded-runner/run/params.ts" rebrand
resolve "src/agents/pi-embedded-subscribe.types.ts" rebrand

# auto-reply
resolve "src/auto-reply/chunk.ts" rebrand
resolve "src/auto-reply/reply/commands-session.ts" rebrand
resolve "src/auto-reply/reply/followup-runner.test.ts" rebrand

# browser
resolve "src/browser/control-auth.ts" rebrand
resolve "src/browser/control-auth.test.ts" rebrand
resolve "src/browser/control-auth.auto-token.test.ts" rebrand
resolve "src/browser/pw-session.browserless.live.test.ts" rebrand
resolve "src/browser/routes/agent.act.ts" rebrand
resolve "src/browser/routes/basic.ts" rebrand

# canvas
resolve "src/canvas-host/a2ui.ts" rebrand

# cli
resolve "src/cli/browser-cli-actions-input/register.files-downloads.ts" rebrand
resolve "src/cli/browser-cli-debug.ts" rebrand
resolve "src/cli/daemon-cli/shared.ts" rebrand
resolve "src/cli/daemon-cli/status.print.ts" rebrand
resolve "src/cli/exec-approvals-cli.ts" rebrand
resolve "src/cli/gateway-cli/run.ts" rebrand
resolve "src/cli/node-cli/daemon.ts" rebrand
resolve "src/cli/nodes-camera.test.ts" rebrand
resolve "src/cli/nodes-screen.ts" rebrand
resolve "src/cli/update-cli/status.ts" rebrand
resolve "src/cli/update-cli/update-command.ts" rebrand
resolve "src/cli/update-cli/wizard.ts" rebrand

# commands
resolve "src/commands/models/auth.ts" rebrand
resolve "src/commands/node-daemon-install-helpers.ts" rebrand

# config
resolve "src/config/types.tools.ts" rebrand

# daemon
resolve "src/daemon/service-env.ts" rebrand
resolve "src/daemon/service-env.test.ts" rebrand

# gateway
resolve "src/gateway/auth.ts" rebrand
resolve "src/gateway/auth.test.ts" rebrand
resolve "src/gateway/boot.test.ts" rebrand
resolve "src/gateway/server-methods/chat.ts" rebrand
resolve "src/gateway/server-runtime-config.ts" rebrand
resolve "src/gateway/server.impl.ts" rebrand
resolve "src/gateway/test-helpers.mocks.ts" rebrand

# hooks
resolve "src/hooks/bundled/boot-md/HOOK.md" rebrand
resolve "src/hooks/internal-hooks.ts" rebrand

# infra
resolve "src/infra/shell-env.ts" rebrand
resolve "src/infra/shell-env.test.ts" rebrand

# media / memory
resolve "src/media/server.test.ts" rebrand
resolve "src/memory/manager.async-search.test.ts" rebrand

# node-host
resolve "src/node-host/invoke.ts" rebrand

# scripts / agents skills (rebrand text)
resolve "scripts/pr" rebrand
resolve ".agents/skills/PR_WORKFLOW.md" rebrand

echo ""
echo "✓ Auto-resolution complete."
echo ""
echo "=== MANUAL MERGE REQUIRED (7 files) ==="
echo "  Resolve each, then stage + git merge --continue"
echo ""
echo "  1. src/config/types.gateway.ts"
echo "     Fork: adds messageLedger field"
echo "     Upstream: adds 'none' to GatewayAuthMode type"
echo "     Strategy: accept upstream + re-add messageLedger field below GatewayAuthConfig"
echo ""
echo "  2. src/config/zod-schema.ts"
echo "     Fork: renames OpenClawSchema → MinionSchema + adds deprecation alias"
echo "     Upstream: adds z.literal('none') to auth mode union"
echo "     Strategy: keep MinionSchema rename + apply upstream 'none' addition"
echo ""
echo "  3. src/gateway/protocol/schema/cron.ts"
echo "     Fork: adds scope field to CronJobSchema, CronAddParamsSchema, CronJobPatchSchema"
echo "     Upstream: major cron schema refactor (CronSessionTargetSchema, CronWakeModeSchema, etc)"
echo "     Strategy: accept upstream refactor + re-add scope fields to the 3 schemas"
echo ""
echo "  4. src/telegram/bot-handlers.ts"
echo "     Fork: adds getGlobalHookRunner() message_inbound hook integration"
echo "     Upstream: refactors MediaGroupEntry/TelegramUpdateKeyContext imports"
echo "     Strategy: accept upstream imports + keep fork's hook_runner block in message handler"
echo ""
echo "  5. src/hooks/gmail-setup-utils.ts"
echo "     Fork: exports gogCredentialsPaths + adds extractGogClientSecret function"
echo "     Upstream: refactors formatCommandFailure → formatCommandResultInternal"
echo "     Strategy: accept upstream refactor + re-add export keyword + extractGogClientSecret"
echo ""
echo "  6. src/cli/update-cli/shared.ts"
echo "     Fork: DEFAULT_PACKAGE_NAME='@nikolasp98/minion', CORE_PACKAGE_NAMES includes 'minion'+'openclaw'"
echo "     Upstream: adds parseTimeoutMsOrExit function"
echo "     Strategy: accept upstream + keep fork's package name constants"
echo ""
echo "  7. docs/install/index.md (and possibly docs/automation/troubleshooting.md, docs/gateway/configuration-reference.md)"
echo "     Fork: extensive prose rebrand (OpenClaw→Minion, openclaw.ai→minion.ai, command names)"
echo "     Upstream: minor content additions"
echo "     Strategy: resolve by keeping fork rebrand + upstream content additions"
